Add more details about the HighAvailability param and SpotInstances
convox/docs pull request #147
Opened 2022-05-30 13:32 UTC by Twsouza

Add more details about the HighAvailability param and SpotInstances. Also reordering alphabetically.

2022-05-30 16:54 UTC, ddoc commented on docs/reference/rack-parameters.md
> +Whether to enable High Availability mode. This ensure proper resources redundancy to mitigate system failures.
Whether or not to enable..... Choose between failure resiliency and cost efficiency.

2022-05-30 16:55 UTC, ddoc commented on docs/reference/rack-parameters.md
> +The number of EC2 instances in your Rack cluster. It's only used for high available clusters.
This parameter is only used for clusters with HighAvailablity = true

2022-05-30 16:56 UTC, ddoc requested changes

2022-05-30 16:56 UTC, ddoc commented on docs/reference/rack-parameters.md
> +If High Availability is true, the [InstanceCount](#instancecount) is used as initial cluster size. If false, the `NoHaInstanceCount` is used as initial cluster size. Both can be scaled to 1000 instan
If HighAvailability is set to true

2022-06-01 14:47 UTC, heronrs commented on docs/reference/rack-parameters.md
> +The number of EC2 instances in your Rack cluster. This parameter is only used for clusters with HighAvailablity as true.
`HighAvailablity=true` i think you missed this one.

2022-06-01 14:47 UTC, heronrs commented on docs/reference/rack-parameters.md
> +Whether to enable High Availability mode, choose between failure resiliency and cost efficiency. This ensure proper resources redundancy to mitigate system failures.
`Whether or not`

2022-06-01 15:08 UTC, Twsouza commented on docs/reference/rack-parameters.md
> +The number of EC2 instances in your Rack cluster. This parameter is only used for clusters with HighAvailablity as true.
Yeah, I thought that this way would be more clear, I changed it in the last commit.

2022-06-01 15:59 UTC, merged